import { useState } from "react";
import { getCellSequences } from "../utils/constants";
export default function ExploreSection({ data }){
  const[dir,setDir]=useState(null);
  const[hl,setHl]=useState(new Set());
  const[words,setWords]=useState([]);
  const L="SATORAREPOTENETOPERAROTAS".split("");
  const go=d=>{if(dir===d&&d!=="all"){setDir(null);setHl(new Set());setWords([]);return;}setDir(d);const s=d==="all"?getCellSequences("right"):getCellSequences(d);setHl(new Set());let dl=0;s.forEach(seq=>{seq.forEach(idx=>{setTimeout(()=>setHl(p=>new Set([...p,idx])),dl);dl+=80;});});const dd=d==="all"?{words:["SATOR","AREPO","TENET","OPERA","ROTAS"],label:"Row"}:data?.[d];if(dd)setWords(dd.words.map((w,i)=>({word:w,label:(d==="all"?"Row":dd.label)+" "+(i+1),meaning:data?.meanings?.[w]||"",seq:s[i]})));};
  return(<section id="explore" className="min-h-screen flex flex-col items-center justify-center px-6 py-24" style={{background:"radial-gradient(ellipse 50% 40% at 50% 50%,rgba(196,145,90,0.03) 0%,transparent 70%),var(--color-abyss)"}}><p className="font-cinzel text-xs tracking-[0.3em] uppercase text-ember mb-3">Interactive</p><h2 className="font-cinzel text-[clamp(1.8rem,4vw,2.8rem)] font-bold tracking-wider mb-4 text-center">Explore Reading Directions</h2><p className="text-dust text-lg max-w-lg text-center font-light leading-relaxed mb-10">Click a direction to illuminate how the Sator Square reveals its words.</p><div className="grid grid-cols-5 gap-1.5 p-1.5 mb-8">{L.map((ch,i)=><div key={i} className={"w-[clamp(48px,10vw,72px)] h-[clamp(48px,10vw,72px)] flex items-center justify-center font-cinzel text-[clamp(1.2rem,3vw,1.8rem)] font-semibold tracking-wider rounded-sm border transition-all duration-350 "+(hl.has(i)?"bg-gradient-to-br from-[#2a2010] to-[#1a1510] border-ember/55 text-flame scale-[1.06] shadow-[inset_0_0_20px_rgba(196,145,90,0.1),0_0_12px_rgba(196,145,90,0.08)]":"bg-gradient-to-br from-stone to-void border-border text-dust")}>{ch}</div>)}</div><div className="flex flex-wrap justify-center gap-2.5 mb-8">{["right","left","down","up"].map(d=><button key={d} onClick={()=>go(d)} className={"font-cinzel text-xs tracking-[0.12em] uppercase px-5 py-2.5 rounded-sm border cursor-pointer transition-all inline-flex items-center gap-2 "+(dir===d?"bg-ember/10 border-ember text-flame":"bg-stone border-border text-dust hover:border-ember hover:text-ember")}><i className={"fa-solid fa-arrow-"+d}/> {d}</button>)}<button onClick={()=>go("all")} className={"font-cinzel text-xs tracking-[0.12em] uppercase px-5 py-2.5 rounded-sm border cursor-pointer transition-all inline-flex items-center gap-2 "+(dir==="all"?"bg-ember/10 border-ember text-flame":"bg-transparent border-ember text-ember hover:bg-ember/10")}><i className="fa-solid fa-eye"/> Reveal All</button></div><div className="flex flex-wrap justify-center gap-3 min-h-[44px]">{words.map((w,i)=><div key={i} onMouseEnter={()=>w.seq&&setHl(new Set(w.seq))} onMouseLeave={()=>{if(dir)go(dir);else setHl(new Set());}} className={"font-cinzel text-sm tracking-[0.15em] font-semibold px-5 py-2 rounded-sm border transition-all cursor-pointer "+(hl.size===(w.seq?.length||0)&&w.seq?.every(i=>hl.has(i))?"border-ember text-flame bg-ember/8":"border-border text-dust bg-stone")}>{w.word}<span className="block font-cormorant text-xs text-muted font-normal tracking-normal not-italic mt-0.5">{w.meaning}</span></div>)}</div></section>);
}
