import { useRef, useMemo, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, Float, Text } from "@react-three/drei";
import { SATOR_SQUARE } from "../utils/constants";
function LetterBlock({letter,position,index}){const ref=useRef();const[h,setH]=useState(false);useFrame(s=>{if(!ref.current)return;const t=s.clock.getElapsedTime();ref.current.position.y=position[1]+0.18+Math.sin(t*0.8+index*0.3)*0.02;});return(<group ref={ref} position={position}><mesh onPointerOver={()=>setH(true)} onPointerOut={()=>setH(false)} castShadow receiveShadow><boxGeometry args={[0.88,0.3,0.88]}/><meshStandardMaterial color={h?"#3a3025":"#2a2318"} roughness={0.85} metalness={0.1}/></mesh><mesh position={[0,0.16,0]}><planeGeometry args={[0.6,0.6]}/><meshStandardMaterial color={h?"#f0c878":"#c4915a"} emissive={h?"#c4915a":"#3a2a10"} emissiveIntensity={h?0.5:0.2} roughness={0.35} metalness={0.7}/></mesh><Text position={[0,0.17,0.005]} fontSize={0.32} color="#0f0d0a" anchorX="center" anchorY="middle">{letter}</Text></group>);}
function BaseSlab(){return(<mesh position={[0,-0.22,0]} receiveShadow castShadow><boxGeometry args={[6,0.25,6]}/><meshStandardMaterial color="#1a1610" roughness={0.95} metalness={0.05}/></mesh>);}
function Dust(){const n=60;const ref=useRef();const pos=useMemo(()=>{const a=new Float32Array(n*3);for(let i=0;i<n;i++){a[i*3]=(Math.random()-0.5)*8;a[i*3+1]=Math.random()*4-0.5;a[i*3+2]=(Math.random()-0.5)*8;}return a;},[]);useFrame(()=>{if(!ref.current)return;const p=ref.current.geometry.attributes.position.array;for(let i=0;i<n;i++){p[i*3+1]+=0.002;if(p[i*3+1]>3.5)p[i*3+1]=-0.5;}ref.current.geometry.attributes.position.needsUpdate=true;});return(<points ref={ref}><bufferGeometry><bufferAttribute attach="attributes-position" count={n} array={pos} itemSize={3}/></bufferGeometry><pointsMaterial size={0.03} color="#c4915a" transparent opacity={0.4} sizeAttenuation/></points>);}
function Scene(){const L=SATOR_SQUARE.flat();return(<><ambientLight intensity={0.25}/><directionalLight position={[5,8,5]} intensity={1.2} castShadow color="#f5e6d0"/><directionalLight position={[-3,4,-2]} intensity={0.4} color="#c4915a"/><pointLight position={[0,3,0]} intensity={0.5} color="#c4915a" distance={8}/><Float speed={0.3} rotationIntensity={0.08} floatIntensity={0.08}><group rotation={[-Math.PI/2,0,0]}><BaseSlab/>{L.map((l,i)=><LetterBlock key={i} letter={l} position={[(i%5)*1.02-2.04,0,Math.floor(i/5)*1.02-2.04]} index={i}/>)}</group></Float><Dust/><OrbitControls enablePan={false} minDistance={4} maxDistance={12} autoRotate autoRotateSpeed={0.5} maxPolarAngle={Math.PI/1.8}/></>);}
export default function Sator3DViewer(){return(<section id="viewer" className="min-h-screen flex flex-col items-center justify-center px-6 py-24" style={{background:"radial-gradient(ellipse 50% 40% at 50% 50%,rgba(196,145,90,0.04) 0%,transparent 70%),var(--color-abyss)"}}><p className="font-cinzel text-xs tracking-[0.3em] uppercase text-ember mb-3">Three.js Visualization</p><h2 className="font-cinzel text-[clamp(1.8rem,4vw,2.8rem)] font-bold tracking-wider mb-4 text-center">3D Sator Square</h2><p className="text-dust text-lg max-w-lg text-center font-light leading-relaxed mb-8">Drag to rotate, scroll to zoom. An ancient inscription as a 3D stone tablet.</p><div className="w-full max-w-3xl aspect-square rounded-lg overflow-hidden border border-border/50"><Canvas shadows camera={{position:[0,6,6],fov:45}} gl={{antialias:true}} style={{background:"#080706"}}><fog attach="fog" args={["#080706",8,16]}/><Scene/></Canvas></div><p className="text-sm text-muted mt-4 font-cinzel tracking-wider"><i className="fa-solid fa-computer-mouse mr-2 text-ember/60"/> Interactive - click and drag to explore</p></section>);}
